### ISSUE TITLE
Optional Synced Hashtable

### ISSUE THREAD

**Issue by flyboarder** [proxb/PoshRSJob#103]
Hello, I am not currently using this library as I am building a WPF application via PowerShell.

The only limitation preventing me from using it is the ability to work with a SyncedHashtable.

Or is there a way I am not currently aware of?

**Comment by proxb** [comment]
These should work out of the box with one exception: if you do the $Using statement, then you have to wrap it in a parenthesis like so:
```PowerShell
$SyncHashTable = [hashtable]::Synchronized(@{})
$SyncHashTable.Test = 'This is a test'
Start-RSJob -Name Test -ScriptBlock {($using:SyncHashtable).Test = 'This was a test'}
$SyncHashTable
```
The result is that the hash table was modified within the RSJob.

```
Name                           Value
----                           -----
Test                           This was a test
```

**Comment by flyboarder** [comment]
@proxb Got it working with ease, thanks so much for the info and great project!

**Comment by flyboarder** [comment]
@proxb I have noticed there is no way to set a session state variable. I have a module which looks for a global variable and if not present creates it (Module imported into RSJob). This variable is my synced hash, while your example works I cannot later send commands to the window dispatcher. Using this as a guide:

https://learn-powershell.net/2013/04/19/sharing-variables-and-live-objects-between-powershell-runspaces/

**Comment by flyboarder** [comment]
The Main issue being able to set session state variables prior to importing modules.
