### ISSUE TITLE
WPF Forms Dispatcher Invoke

### ISSUE THREAD

**Issue by flyboarder** [proxb/PoshRSJob#104]
New issue to clarify problem: When using WPF Forms getting a "You cannot call a method on a null-valued expression." error.

Using this guide:
https://learn-powershell.net/2013/04/19/sharing-variables-and-live-objects-between-powershell-runspaces/

The problem show itself when trying to run a command on the WPF form from the main thread:
```powershell
$SyncHash.SplashScreen.Window.Dispatcher.Invoke("Normal", [action] { $SyncHash.SplashScreen.Window.Close() })
```

`SyncHash` in this case is null. Doing `($Using:SyncHash)` will hang.

**Comment by proxb** [comment]
That is interesting. I'll have to do some testing and see what might be going on. I know I've seen people use this module for their UIs, but I don't believe anyone has tried doing what you are looking to do yet.

**Comment by flyboarder** [comment]
For reference there is a stackoverflow question about this: http://stackoverflow.com/questions/34440599/using-dispatcher-invoke-with-a-runspace-in-powershell

Prior to using this module the above code worked when `SyncHash` was set via session proxy, I believe exposing an option to set variables in this manner will solve it as the variables would then be available to the whole runspace and not local to the script block.

**Comment by flyboarder** [comment]
I was able to get this working just now. The solution is a below:

```powershell
$ScriptBlock = { 

      $Global:SyncHash = ($Using:SyncHash)

      $SplashScreen = ##WPF XAML -> Window
      $SyncHash.SplashScreen = $SplashScreen
      $SplashScreen.ShowDialog() | Out-Null
    
    }

## Show Initial WPF Window
Start-RSJob -Name "SplashScreenOpen" -ScriptBlock $ScriptBlock
```
```powershell
$ScriptBlock = {

  ## Pull in Syncronized Hashtable
  $Global:SyncHash = ($Using:SyncHash)
  
  ## First we monitor the $SyncHash.SyncRoot
  [System.Threading.Monitor]::Enter($SyncHash.SyncRoot)
  
  ## Second the [action] must be unbound from the thread by using [scriptblock]::create
  ## this avoids the thread from hanging.
  $SyncHash.SplashScreen.Window.Dispatcher.Invoke("Normal", [action][scriptblock]::create({ 
      
    ## Invoke WPF events etc.
    ## This is done within the WPF owner thread
    $SyncHash.SplashScreen.Window.Close()
      
  }))
        
  ## Third we remove the monitor on $SyncHash.SyncRoot
  [System.Threading.Monitor]::Exit($SyncHash.SyncRoot)
}

## Finally we call this script block as yet another RSJob thread, to close WPF Window
Start-RSJob -Name "SplashScreenClose" -ScriptBlock $SplashClose
```
