### ISSUE TITLE
The property 'Arguments' cannot be found on this object

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#110]
I had weird spurious errors today on 1.7.2.7.

Exception calling "EndInvoke" with "1" argument(s): "The property 'Arguments' cannot be found on this object. Verify
that the property exists."
At line:11 char:21
+                     $Data = $job.InnerJob.EndInvoke($job.Handle)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CmdletInvocationException

I run with Set-StrictMode -Version Latest and $ErrorActionPreference = "Stop".

But I had a look through this line of code and I couldn't see how this part would even touch an Arguments property unless it's buried in some other section of code...

I had the issue for a while, and then it disappeared as quickly as it came. I'm raising this issue in case others see it or to track any further occurrences. I haven't been able to force it to happen hence the vagueness.

**Comment by proxb** [comment]
I can pretty much reproduce this with the following code;

```PowerShell
1|Start-RSJob {
    $ErrorActionPreference='stop'
    $_/0
}|Wait-RSJob|Receive-RSJob
```

**Error:**
```
WriteStream : Exception calling "EndInvoke" with "1" argument(s): "Attempted to 
divide by zero."
At C:\Users\proxb\Documents\WindowsPowerShell\Modules\PoshRSJob\Public\Receive-RSJob
.ps1:105 char:18
+             $_ | WriteStream
+                  ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,WriteStream
```

Looks like something in WriteStream might be causing this when `ErrorActionPreference='stop'` is used within the scriptblock.

**Comment by proxb** [comment]
It seems like the error stream from within in the runspace is creating a false positive that an error is happening when EndInvoke() is called.

```PowerShell
$RS = [runspaceFactory]::CreateRunspace()
$PS = [powershell]::Create()
$RS.Open()
$PS.Runspace = $RS
$Null = $PS.AddScript({
    $ErrorActionPreference = 'Stop'
    1/0
})
$Handle = $PS.BeginInvoke()
$Results = $PS.EndInvoke($Handle)
$PS.dispose()
```

```
Exception calling "EndInvoke" with "1" argument(s): "Attempted to divide by zero."
At line:1 char:1
+ $PS.EndInvoke($Handle)
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException
```

I'm not sure of a good way to get around this just yet and more research will be needed.

**Comment by codykonior** [comment]
I don't think that's the same error.

I use a modified version of PoshRSJob with this code in WriteStream:

>                 Switch ($Stream) {
>                     "Verbose" { $IndividualJob | Select -ExpandProperty Verbose | Where { $_.Message } | ForEach { Write-Verbose $_ } }
>                     "Warning" { $IndividualJob | Select -ExpandProperty Warning | Where { $_.Message } | ForEach { Write-Warning $_ } }
>                     "Error"   { $IndividualJob | Select -ExpandProperty Error | ForEach { $_ } }
>                     "Output"  { $IndividualJob | Select -ExpandProperty Output }
>                 }
> 

Here's my output when I run your test:

> Exception calling "EndInvoke" with "1" argument(s): "Attempted to divide by zero."
> At line:11 char:21
> +                     $Data = $job.InnerJob.EndInvoke($job.Handle)
> +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : RuntimeException

That's an Output notification not an Error one. That's what I'd raised on a separate issue though I'm not sure if others would like it as it's not a great idea to pollute the Output stream.

The error recurred again today. I've found it happens if I have a large number of jobs queued (on a 4 core machine with 10 jobs running and a few hundred queued across two PowerShell sessions). Now that I know this I can reliably / randomly generate it plus catch stack traces.

> ErrorRecord                 : The property 'Arguments' cannot be found on this object. Verify that the property exists.
> StackTrace                  :    at CallSite.Target(Closure , CallSite , Object )
>                                  at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
>                                  at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame 
>                               frame)
>                                  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
>                               retedFrame frame)
> WasThrownFromThrowStatement : False
> Message                     : The property 'Arguments' cannot be found on this object. Verify that the property exists.
> Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
> InnerException              : 
> TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, 
>                               System.Exception)
> HelpLink                    : 
> Source                      : System.Management.Automation
> HResult                     : -2146233087
> 
> 
> 
> 
> *****
> 
> 
> ErrorRecord                 : The property 'Arguments' cannot be found on this object. Verify that the property exists.
> StackTrace                  :    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate
>                               (Object input, Hashtable errorResults, Boolean enumerate)
>                                  at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean 
>                               ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] 
>                               pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
>                                  at Test-DbReportServer<Process>(Closure , FunctionContext )
> WasThrownFromThrowStatement : False
> Message                     : The property 'Arguments' cannot be found on this object. Verify that the property exists.
> Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
> InnerException              : System.Management.Automation.PropertyNotFoundException: The property 'Arguments' cannot 
>                               be found on this object. Verify that the property exists.
>                                  at 
>                               System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
>                               funcContext, Exception exception)
>                                  at 
>                               System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
>                               frame)
>                                  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
>                               retedFrame frame)
>                                  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
>                               retedFrame frame)
>                                  at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
>                                  at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
>                                  at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
>                               dollarUnderbar, Object inputToProcess)
>                                  at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
>                                  at System.Management.Automation.CommandProcessorBase.Complete()
> TargetSite                  : Void EndInvoke()
> HelpLink                    : 
> Source                      : System.Management.Automation
> HResult                     : -2146233087
> 
> 
> 
> 
> *****
> 
> 
> ErrorRecord                 : Exception calling "EndInvoke" with "1" argument(s): "The property 'Arguments' cannot be 
>                               found on this object. Verify that the property exists."
> StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationExceptio
>                               n(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo 
>                               memberInfo)
>                                  at CallSite.Target(Closure , CallSite , Object , Object )
>                                  at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
> WasThrownFromThrowStatement : False
> Message                     : Exception calling "EndInvoke" with "1" argument(s): "The property 'Arguments' cannot be 
>                               found on this object. Verify that the property exists."
> Data                        : {}
> InnerException              : System.Management.Automation.CmdletInvocationException: The property 'Arguments' cannot 
>                               be found on this object. Verify that the property exists. ---> 
>                               System.Management.Automation.PropertyNotFoundException: The property 'Arguments' cannot 
>                               be found on this object. Verify that the property exists.
>                                  at 
>                               System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
>                               funcContext, Exception exception)
>                                  at 
>                               System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
>                               frame)
>                                  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
>                               retedFrame frame)
>                                  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
>                               retedFrame frame)
>                                  at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
>                                  at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
>                                  at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
>                               dollarUnderbar, Object inputToProcess)
>                                  at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
>                                  at System.Management.Automation.CommandProcessorBase.Complete()
>                                  --- End of inner exception stack trace ---
>                                  at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
>                                  at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
>                                  at CallSite.Target(Closure , CallSite , Object , Object )
> TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, 
>                               System.Exception)
> HelpLink                    : 
> Source                      : System.Management.Automation
> HResult                     : -2146233087
> 
> 
> 
> 
> *****
> 
> 
> MyCommand             : 
> BoundParameters       : {}
> UnboundArguments      : {}
> ScriptLineNumber      : 11
> OffsetInLine          : 21
> HistoryId             : -1
> ScriptName            : 
> Line                  :                     $Data = $job.InnerJob.EndInvoke($job.Handle)
>                         
> PositionMessage       : At line:11 char:21
>                         +                     $Data = $job.InnerJob.EndInvoke($job.Handle)
>                         +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> PSScriptRoot          : 
> PSCommandPath         : 
> InvocationName        : 
> PipelineLength        : 0
> PipelinePosition      : 0
> ExpectingInput        : False
> CommandOrigin         : Internal
> DisplayScriptPosition : 
> 
> 
> 
> 
> *****
> 
> 
> PSMessageDetails      : 
> Exception             : System.Management.Automation.MethodInvocationException: Exception calling "EndInvoke" with "1" 
>                         argument(s): "The property 'Arguments' cannot be found on this object. Verify that the 
>                         property exists." ---> System.Management.Automation.CmdletInvocationException: The property 
>                         'Arguments' cannot be found on this object. Verify that the property exists. ---> 
>                         System.Management.Automation.PropertyNotFoundException: The property 'Arguments' cannot be 
>                         found on this object. Verify that the property exists.
>                            at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
>                         funcContext, Exception exception)
>                            at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
>                         frame)
>                            at 
>                         System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
>                         frame)
>                            at 
>                         System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
>                         frame)
>                            at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
>                            at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
>                            at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
>                         dollarUnderbar, Object inputToProcess)
>                            at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
>                            at System.Management.Automation.CommandProcessorBase.Complete()
>                            --- End of inner exception stack trace ---
>                            at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
>                            at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
>                            at CallSite.Target(Closure , CallSite , Object , Object )
>                            --- End of inner exception stack trace ---
>                            at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
>                         funcContext, Exception exception)
>                            at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
> TargetObject          : 
> CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> FullyQualifiedErrorId : CmdletInvocationException
> ErrorDetails          : 
> InvocationInfo        : System.Management.Automation.InvocationInfo
> ScriptStackTrace      : at <ScriptBlock>, <No file>: line 11
> PipelineIterationInfo : {}

**Comment by codykonior** [comment]
You know what give me a little bit - I think I found the problem in my own code :-(

**Comment by codykonior** [comment]
Confirmed, this is a non-issue. It turns out what I wrote to write stack traces was occasionally throwing the error. Nevermind.
