### ISSUE TITLE
TabExpansion puts a small error in $error

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#112]
If you import PoshRSJob and check $error[0] you'll find this:

> Get-Variable : Cannot find a variable with the name 'Options'.
> At ...\PoshRSJob\Scripts\TabExpansion.ps1:20 char:11
> - If (-not (Get-Variable -Scope Global -Name Options -ErrorAction:Silen ...

It's not an error, of course. But if you wanted to avoid putting extraneous stuff into $error you can do the check in a different way; with Get-Variable -Scope Global | Where { $_.Name -eq "Options" }.

**Comment by proxb** [comment]
Fix is in queue for the next version update.
