### ISSUE TITLE
Vnext TFS 2015 Streaming Progress

### ISSUE THREAD

**Issue by sheldonhull** [proxb/PoshRSJob#113]
I'm having trouble identifying the right way to stream just the internal verbose output without the script block contents, making it difficult to review the log output. 

Currently I use: 

```
$dbList | Start-RSJob -Verbose -Throttle 3 -FunctionsToLoad Foo-Bar -ArgumentList $ValuesToImport,$CheeseFeet -ScriptBlock {
    [cmdletbinding()]
 param($ValuesToImport,$CheeseFeet
$DoReallyCoolStuffHere
write-verbose "Stuff I want to to read in output"
write-host "I know this has issues right now, but I could wish"
write-error "Issues in output of course, but it's so awesome i'm sure it will be fixed someday"

} | Wait-RSJob|Receive-RSJob 
```

**Comment by sheldonhull** [comment]
As an update, when I avoid write-host or write-verbose and instead do the output with no stream designation like 

"write this message"
instead of
write-host "write this message" 
the output is successful. Still trying to understand why this is.

**Comment by proxb** [comment]
Yea, the streams are acting weird and I haven't had the time yet to really dive into things. I'm hoping to get more time in the coming weeks to see if I can figure something out.

**Comment by proxb** [comment]
@sheldonhull Take a look  at the latest updates that I made for this (v1.7.3.2) that might meet what you are looking at. Write-Host is something that I am still looking at but it probably won't happen for a while.

**Comment by sheldonhull** [comment]
I apologize, as I'm probably missing the notes on it. What specifically was done that I can test with? 
I've reverted for now to using Invoke-Parallel from PSParallel as it works with little configuration. However, I know you have this under active development and are working on it, so I'd rather go with this as it's being improved/updated. I'm just confused a bit on streaming back the write-host progress, which is needed with the TFS 2015 build process to report progress percentage. 

Let me know so I can help in anyway I can and know what to look for.

**Comment by proxb** [comment]
I've done more fixing with the `Write-Verbose` piece that you had mentioned in an earlier post so it should work better. The `Write-Host' piece is a little more challenging to fit into the current module, but I am still working to find a usable solution.

**Comment by proxb** [comment]
> As an update, when I avoid write-host or write-verbose and instead do the output with no stream designation like
> 
> "write this message"
> instead of
> write-host "write this message" 
> the output is successful. Still trying to understand why this is.

This is because using `"write this message"` is outputting a string which is an object that is sent back from the runspace whereas `write-host "write this message" ` is writing to the console which doesn't get sent out of the runspace.

**Comment by sheldonhull** [comment]
I'll have to take a look. 
I am now ensuring I use write-information, write-verbose, write-warning, and write-error. 

Should all of these streams be properly handled? 
Lastly, if I experience nd error, do you have any tip/recommendation on trying to rerun those specific threads.

**Comment by sheldonhull** [comment]
My initial look is good. I'm having some issues getting the verbose and debug streams back

Simple example I wanted to test

```
 } | Wait-RSJob -ShowProgress -verbose:$False | ForEach {
       
           write-debug ($_ | select Name, State, HasErrors | format-table -autosize -Wrap | out-string)
           write-debug ("--- Job Output ---- `n`n" )          
              
           $_.Verbose | %{ write-verbose $_}
           $_.Debug | %{ write-debug $_}

          if ($_.HasErrors -eq $true) {
                                        write-error("$($_.Error[0].InvocationInfo.InvocationName) : Line $($_.Error[0].InvocationInfo.PositionMessage)")
                                        $_.Error | %{write-error ($_)}
                                        
                                        throw
                                        }
      }
```

**Comment by sheldonhull** [comment]
Success with verbose and debug streams. However, errors are a tough one. I'm seeing the verbose/debug output seemingly cleared when an error is thrown so no output seems to be visible. I'll update with further information if I can provide a better example.

**Comment by sheldonhull** [comment]
Closing after adding this wiki snippet from another user that provided something that is working for me now to output the error detail with detail now. 

Opened separate request for consideration on information stream, or if i get time to eventually contribute I'll try to help.
