### ISSUE TITLE
Passing an empty batch to Wait-RSJob stops all further processing in the caller

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#119]
This is a bug. Reproduce with an unused batch number such as:

```
Get-RSJob -Batch "123" | Wait-RSJob; "Hi";
```

Does not show Hi. All processing in any caller (like a function) stops at this point because the caller exits. It's caused by Line 119 in Wait-RSJob.ps1

```
        If ($List.count -eq 0) {
            BREAK
        }  
```

It seems that break here has pretty bad (for me) unintended consequences. Replacing it with a return appears to work better.

**Comment by proxb** [comment]
@codykonior This should be fixed now, please test and let me know the results.

**Comment by codykonior** [comment]
Yes it's fixed.

**Comment by nathanmjones** [comment]
1.7.3.6 did the trick.. thanks v much
