### ISSUE TITLE
Tried updating to 1.7.3.5 , Get-Module still shows 1.7.2.9

### ISSUE THREAD

**Issue by hou8182** [proxb/PoshRSJob#123]
I did a Remove-Module PoshRSJob  and deleted all of the files from the PoshRSJob folder. I then extracted the 1.7.3.5 files from the downloaded zip file and placed them in the PoshRSJob folder. Next, I did an Import-Module PoshRSJob, but when I run Get-Module it still shows the old 1.7.2.9 version. I'm not sure what I am doing wrong.

**Comment by MVKozlov** [comment]
`Get-Module PoshRSJob | Select-Object -ExpandProperty Path`
Is the right path showed ?

**Comment by hou8182** [comment]
Thanks, you solved my issue. I was running powershell with my admin account
and it was looking under the documents path rather than through program
files for the module.
