### ISSUE TITLE
Is this correct way to utilize mutex for multi-file threading?

### ISSUE THREAD

**Issue by sheldonhull** [proxb/PoshRSJob#128]
I'm unclear on the correct usage from reading through past issues. I'm struggling to get solid error handling inside runspaces, so I'm hoping someone could validate this is the correct way to pass in a mutex to ensure no issues. I haven't seen any issues so far, but again, my error handling with runspaces is very poor at this point. 

```

$mtx = New-Object System.Threading.Mutex($false, "TestMutex")
$table | select -ExpandProperty BatchedGroup | PoshRSJob\Start-RSJob -throttle 1 -verbose:$true -argumentlist ($arg1,$arg2,$mtx) -ModulesToImport ('PSExcel') -scriptblock {
param (
   $Arg1
  ,$Arg2
  ,$mtx
)

#... do stuff



  $mtx.WaitOne()
  $datarows |  Export-Csv -Path "C:\Temp\$($Arg1)_$($TestFileName).csv" -append -NoTypeInformation   
  $mtx.ReleaseMutex()

  } | Wait-RSJob -ShowProgress -verbose:$false
```

**Comment by codykonior** [comment]
Looks fine to me. Does it work?

At the end of the script you should $mtx.Dispose()

**Comment by sheldonhull** [comment]
Thank you. That's helpful. I'm not sure, but I see a lot of github projects having "issues" as a knowledge base. Is there a way to migrate or tag these knowledge base items over to the wiki. This is a fantastic project, but I'm seriously challenged in handling the error output and debugging part. Some tips and advice for newbies looking to leverage your expertise would be awesome. Thanks again!

**Comment by proxb** [comment]
@sheldonhull I'll have to look at creating a tag for these as being a candidate to put in a Wiki. I admit-tingly haven't done much with the Wiki since I created it and had hopes that others would be able to help out with expanding it.

**Comment by sheldonhull** [comment]
Nice. I don't have a problem in trying to help piece by piece. I'm planning on blogging on this further (already did one), but I've been uncomfortable with understanding error handling in this. That's my biggest hurdle to properly using in most of my work. 

Really appreciate all the hard work!
