### ISSUE TITLE
Not handling single parameter in ArgumentList correctly

### ISSUE THREAD

**Issue by grantemsley** [proxb/PoshRSJob#132]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When a single parameter is passed with -ArgumentList, the parameter does not get set, instead $_ does.

Start-RSJob seems to have some special logic for having a single argument, but I haven't read it closely enough to understand what it's doing there.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

When I have multiple parameters, it works as expected:

`PS X:\> Start-RSJob -ScriptBlock{ param($test1, $test2); write-output "Argument $test1 and $test2 were passed" } -ArgumentList 'hello','goodbye' | wait-rsjob | receive-rsjob`
Output:
`Argument hello and goodbye were passed`

**But with a single parameter, it does not:**
`Start-RSJob -ScriptBlock{ param($test); write-output "Argument $test was passed" } -ArgumentList 'hello' | wait-rsjob | receive-rsjob`
Output:
`Argument  was passed`

My argument seems to end up in in `$_` instead of `$test` for some reason:
`PS X:\> Start-RSJob -verbose -ScriptBlock{ param($test); write-output "Argument $test was passed, so was $_" } -ArgumentList 'hello' | wait-rsjob | receive-rsjob`
Output:
`Argument  was passed, so was hello`

**What is the expected behavior?**

In the second example, $test should be set, so the output should be `Argument hello was passed, so was`

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

PoshRSJob 1.7.3.7, Windows 10 with updates, powershell version 5.1.14393.693
Have not tried under any other configuration.

**Comment by MVKozlov** [comment]
Can confirm this. Single parameter handled incorrectly.
Moreover, using example from #133 we can get strange results:

```
 D:\> $hash = [hashtable]::Synchronized(@{Number=0})
     $sb = {
           param($syncHash)
           $syncHash.GetType()
           [System.Threading.Monitor]::Enter($syncHash.SyncRoot)
           $syncHash.Number += 10
           [System.Threading.Monitor]::Exit($syncHash.SyncRoot)
     }
     1..3 | Start-RSJob -Name {$_} -ScriptBlock $sb -ArgumentList $hash | Wait-RSJob | Receive-RSJob
Exception calling "Enter" with "1" argument(s): "Значение не может быть неопределенным."
The property 'Number' cannot be found on this object. Verify that the property exists and can be set.
Exception calling "Exit" with "1" argument(s): "Значение не может быть неопределенным."

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType
Exception calling "Enter" with "1" argument(s): "Значение не может быть неопределенным."
The property 'Number' cannot be found on this object. Verify that the property exists and can be set.
Exception calling "Exit" with "1" argument(s): "Значение не может быть неопределенным."
True     True     Int32                                    System.ValueType
Exception calling "Enter" with "1" argument(s): "Значение не может быть неопределенным."
The property 'Number' cannot be found on this object. Verify that the property exists and can be set.
Exception calling "Exit" with "1" argument(s): "Значение не может быть неопределенным."
True     True     Int32                                    System.ValueType

```

Declaring second parameter in scriptblock save from errors

 ```
D:\> $hash = [hashtable]::Synchronized(@{Number=0})
    $sb = {
           param($syncHash, $a)
           $syncHash.GetType()
           [System.Threading.Monitor]::Enter($syncHash.SyncRoot)
           $syncHash.Number += 10
           [System.Threading.Monitor]::Exit($syncHash.SyncRoot)
    }
    1..3 | Start-RSJob -Name {$_} -ScriptBlock $sb -ArgumentList $hash | Wait-RSJob | Receive-RSJob

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    True     SyncHashtable                            System.Collections.Hashtable
False    True     SyncHashtable                            System.Collections.Hashtable
False    True     SyncHashtable                            System.Collections.Hashtable

```

**Comment by MVKozlov** [comment]
I found where is a logic error. If script have only one argument, this argument used for pipeline input even if the scriptblock doesn't support pipeline input.

so, it's poorly documented 'feature'

btw, @proxb , code
`If (@($ArgumentList).count -match '0|1') {`
is buggy and ugly :) in next versions please change it to **-le 1** :)

**Comment by proxb** [comment]
@MVKozlov Yea, I don't know where that came from. I chalk it up to a late night coding session and just wanted to make it work. :)

**Comment by proxb** [comment]
I found the offending line of code that is causing this to break. It appears that one of the PRs that came through made an update that broke this. I'll try to get this uploaded by the weekend. Also will fix the code mentioned by @MVKozlov wrt using `-match 0|1`

**Comment by proxb** [comment]
This should be fixed in the latest release.
