### ISSUE TITLE
Passing synchronized hashtable as argument does not work

### ISSUE THREAD

**Issue by kborowinski** [proxb/PoshRSJob#133]
I would like to reopen issue #45 as passing synchronized hashtable as argument does not work.
_Update:_ I guess this behaviour may be related to issue #132.

This does not work:
```powershell
$hash = [hashtable]::Synchronized(@{Number=0})
$sb = {
	param($syncHash)
	[System.Threading.Monitor]::Enter($syncHash.SyncRoot)
	$syncHash.Number += 10
	[System.Threading.Monitor]::Exit($syncHash.SyncRoot)
}
1..10 | Start-RSJob -Name {$_} -ScriptBlock $sb -ArgumentList $hash | Wait-RSJob | Receive-RSJob
```
Error:
```powershell
Exception calling "Enter" with "1" argument(s): "Value cannot be null."
The property 'Number' cannot be found on this object. Verify that the property exists and can be set.
Exception calling "Exit" with "1" argument(s): "Value cannot be null."
...
```

This works perfectly:
```powershell
$hash = [hashtable]::Synchronized(@{Number=0})
$sb = {
	($using:hash).Number += 10
}
1..10 | Start-RSJob -Name {$_} -ScriptBlock $sb | Wait-RSJob | Receive-RSJob
```
Components:
Powershell 5.0
PoshRSJob 1.7.3.7

**Comment by jgmmi** [comment]
I would like to indicate that this problem exists for me in PoshRSJob 1.7.3.7 and PowerShell 5.1 (WMF 5.1).

For now, I'm using PoshRSJob 1.7.3.3 without problems.

**Comment by proxb** [comment]
Interesting, I will look at 1.7.3.3 and see what differences there are with the code.

**Comment by proxb** [comment]
I found the offending line of code that is causing this to break. It appears that one of the PRs that came through made an update that broke this. It is directly related to #132

**Comment by proxb** [comment]
This should be fixed in the latest release
