### ISSUE TITLE
Logic error with $IsPipeline variable ?

### ISSUE THREAD

**Issue by MVKozlov** [proxb/PoshRSJob#134]
while reviewing code for #132 I'm found that $IsPipeline always resolves to $true
lines 246 to 267:
```
        If ($PSBoundParameters.ContainsKey('InputObject')) {            
            $IsPipeline = $True
        } 
        ElseIf ($PSCmdlet.SessionState.PSVariable.Get('_')) {
            $IsPipeline = $True
        }
        Else {
            $IsPipeline = $True
        }
```
Lines 271 to 280
```
        Write-Debug "[PROCESS]"       
        If ($IsPipeline -AND $PSBoundParameters.ContainsKey('InputObject') -AND -NOT $IgnoreProcess) {
            [void]$List.Add($InputObject)
        } 
        ElseIf ($IgnoreProcess) {
            $IsPipeline = $True
        }
        Else {
            $IsPipeline = $True
        }

```
what's the catch ?

**Comment by proxb** [comment]
I'll have to go back and look at some of my older code and see what all has changed. I thought that I had it set $False at some point in time.

**Comment by MVKozlov** [comment]
here it is
https://github.com/proxb/PoshRSJob/commit/f14b4968507a16ab1b141c74b1f89d09c2d35f46

all in all parameter handling looks very itricately

I can take a closer look into it but I want to understand logic first.

We have three main variable factors:
1. $InputObject/$_/Pipeline (yes/no)
2. $ArgumentList  (0,1,many)
3. $Scriptblock param (0,1,many)

and we have three and half final states:

1. prepend $_ into $scriptblock params and push pipeline into it
2. push pipeline into first $scriptblock param
3. ignore pipeline and do direct $arg -> $sb param mapping
   3a. $argumentList.Count <>($scriptblock params).count ??


This is correct ?
May be we can open wiki page and build states table for future coding (and cover it by tests ;-) )

**Comment by MVKozlov** [comment]
Have some time to look closer...
As far I see the idea was 
1. get InputObject/pipeline if it possible (into $list)
2. prepend $_ into ScriptBlock params if arglist count greater than ScriptBlock params count
3. start jobs

If I correctly understood the idea, there is a bumch of problems with implementation
When you will bless me to the feat ;-)  I try to implement strict solution and tests (in fact I already have tests for idea above)

**Comment by MVKozlov** [comment]
Another v2 error (I continue to report here)
`ConvertScriptBlockV2` does not support `$v -is [type] syntax`
```
PS D:\> $a = 1; $a -is [array]
False
PS D:\> $a | Start-RSJob { $_ -is [array] }
Create : Exception calling "Create" with "1" argument(s): "You must provide a value expression on the right-hand side o
f the '-is' operator."
At PoshRSJob\Private\ConvertScriptBlockV2.ps1:88 char:26
```
workaround: `$_ -is "array"`
