### ISSUE TITLE
Wait-RSJob is not working with parameter set Name or ID.  

### ISSUE THREAD

**Issue by exactmike** [proxb/PoshRSJob#139]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Wait-RSJob goes into an unending loop when any parameter set other than Job.  It also throws a divide by zero error if the -State parameter is used. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I'm testing on Powershell 5.1.14393.953 on Windows 10. Have not tested anywhere else but this does not look to be version specific

**Please provide a code example showing the issue, if applicable:**
```PowerShell
#Code goes here
# Works
$jobs = @(
foreach ($num in 1..5)
{
    $SleepSeconds = $num * 5
    Start-RSJob -ScriptBlock {Start-Sleep -Seconds $using:sleepseconds}  -Name "Sleep$num"
}
)
Wait-RSJob -Job $jobs -verbose #-showprogress
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob
# None of these Work
$jobs = @(
foreach ($num in 1..5)
{
    $SleepSeconds = $num * 5
    Start-RSJob -ScriptBlock {Start-Sleep -Seconds $using:sleepseconds}  -Name "Sleep$num"
}
)
Wait-RSJob -Name $jobs.name -verbose
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob
$jobs = @(
foreach ($num in 1..5)
{
    $SleepSeconds = $num * 5
    Start-RSJob -ScriptBlock {Start-Sleep -Seconds $using:sleepseconds}  -Name "Sleep$num"
}
)
Wait-RSJob -id $jobs.id -verbose
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob
$jobs = @(
foreach ($num in 1..5)
{
    $SleepSeconds = $num * 5
    Start-RSJob -ScriptBlock {Start-Sleep -Seconds $using:sleepseconds}  -Name "Sleep$num"
}
)
Wait-RSJob -InstanceID $jobs.InstanceID -Verbose
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob
$jobs = @(
foreach ($num in 1..5)
{
    $SleepSeconds = $num * 5
    Start-RSJob -ScriptBlock {Start-Sleep -Seconds $using:sleepseconds}  -Name "Sleep$num" -Batch 'Sleepy'
}
)
Wait-RSJob -Batch 'Sleepy' -Verbose
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob

**Comment by MVKozlov** [comment]
Seems this never works :)
even 1.4.3.0 have the same non-working codebase
Receive-RSJob have slightly modified code that works.

**Comment by proxb** [comment]
I'll have to take a look at this. I never wrote this one (user submitted) but will look at using the Receive-RSJob code as a possible solution for this function.

**Comment by proxb** [comment]
It looks like $List should be replaced with PoshRS_Jobs and it will work as intended. I made the change and tested successfully with all of the examples that OP provided.

```PowerShell
$FilteredJobs = @($PoshRS_Jobs | Where-Object $ScriptBlock)
```

**Comment by MVKozlov** [comment]
I think for 'Job' parameterset you can exclude filtering at all ($FilteredJobs = $List) and others stay as it is now. /speedup/
