### ISSUE TITLE
Wait-RSJob doesn't sleep

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#140]
**Do you want to request a *feature* or report a *bug*?**
Both.

**What is the current behavior?**
Wait-RSJob doesn't sleep between completed job checks in its Do/While loop. So it's probably consuming a lot of CPU needlessly.

**What is the expected behavior?**
It should probably sleep but I'm not sure for how long. 0.5 - 1s would be fine. Anything is better than what it does now.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Current but it goes back a while.

**Comment by codykonior** [comment]
I added to Wait-RSJob line 192.

```
if($WaitJobs){
    Start-Sleep -Milliseconds 500
}
```

I tested:

```
Import-Module PoshRSJob -Force; Measure-Command { 1..8 | Start-RSJob { Start-Sleep -Seconds 4 } -Throttle 4 | Wait-RSJob }
```

Prior to the change CPU on one core jumps to 100%. After the change it idles at 10%. Completion times for the query before and after are the same.

So before any

**Comment by MVKozlov** [comment]
After a close look at `Wait-RSJob` I dont like it at all :)
I dont like the `-match` used in `$FilterScript` and `$FilterScript` itself

``` powershell
# Preparation:
$all = 1..100000 | %{  [PSCustomObject]@{ID=$_; Name="Name$_"; Guid=[Guid]::NewGuid().ToString()} }
$wn = 1..50 | %{ Get-Random -Minimum 1 -Maximum 99999 }
$wn = $all[$wn]
$m = '^' + ($wn.Name -join '$|^') + '$'
$wn_name = $wn.Name
$hash = @{}; $wn.Name | %{ $hash[$_] = 1 }
# Measurements:
 C:\> measure-command { $all | ?{ $_.Name -match $m} }
Seconds           : 3
Milliseconds      : 50
C:\> measure-command { $all | ?{ $wn_name -contains $_.Name } }
Seconds           : 3
Milliseconds      : 682
C:\> measure-command { $all | ?{ $hash.ContainsKey($_.Name) } }
Seconds           : 2
Milliseconds      : 675
# !!!!
 C:\> measure-command { $all.where( { $hash.ContainsKey($_.Name) } ) }
Seconds           : 0
Milliseconds      : 870
C:\> measure-command { foreach ($a in $all) { if ( $a.Name -match $m ) { $a } } }
Seconds           : 0
Milliseconds      : 648
 C:\> measure-command { foreach ($a in $all) { if ( $wn_name -contains $a.Name ) { $a } } }
Seconds           : 1
Milliseconds      : 245
C:\> measure-command { foreach ($a in $all) { if ( $hash.ContainsKey($a.Name) ) { $a } } }
Seconds           : 0
Milliseconds      : 293
```
Last is the absolute winner!
so code should looks like
``` powershell
$hash = @{}
# collect $hash like collect $list now, set $property
# [...]
# and filter like
$jobs = foreach ($job in $PoshRS_jobs) {
   if ($Hash.ContainsKey($job.$property)) {
     $job
   }
}
```

If i have a time today I write it :)

**Comment by codykonior** [comment]
Wait-RSJob still needs a sleep.

**Comment by proxb** [comment]
Leave a comment
