### ISSUE TITLE
-RSJob question

### ISSUE THREAD

**Issue by MVKozlov** [proxb/PoshRSJob#141]
@proxb , while I rewrite Wait-RSJob, I have some thoughts

1.  Is `Wait-RSJob` really need `-State` and `-HasMoreData` parameters ?
2.  Do you like my `Wait-` version ? It can be moved into `Get-RSJob`
3. May be all of `Wait-`, `Receive-`, `Remove-` and `Stop-` should be rewritten in the same way like
``` powershell
begin {
# Collect parameters
}
process {
# Collect pipeline parameters
}
end {
   $Jobs = Get-RSJob @PSBoundParameters
   # Do Wait/Receive/Stop/Remove stuff
}
```
I think maintainability will be better

**Comment by proxb** [comment]
@MVKozlov 
1) I'm fine with removing HasMoreData (not even sure why it is needed, but I didn't create this function) but would prefer to keep -State for right now to keep it similar to the PSJobs cmdlets.
2) I think it looks good. Haven't tested yet but from the comments it appears to be running faster than the current version.
3) I'm fine with the change in code for the other functions that you have mentioned.
