### ISSUE TITLE
Current build has job hang issues

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#143]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm experiencing massive amount of job hangs (hundreds of jobs across two servers) when running the current source committed to GitHub (last commit April 11). It goes away when reverting to 1.7.3.7.

I haven't had much luck reproducing it but it's definitely happening.

**Comment by MVKozlov** [comment]
seems @proxb busy there days, but significant changes was inspired by me and I have some time :)
any details to share ?
PS version, hang conditions ?
It hang somewhere iside a job itself or at `-RSJob` command ?
- It can hang at any time ?
- it can happen at job starting, removing, ?
- 2 minutes after starting (cleanup) ?
- if you take latest version, edit PoshRSJob/PoshRSJob.psm1,  move `$job.Completed = $True` from line 163 back to 1.7.3.7 place (right after $job.InnerJob.dispose(), line 156 ) it solve your problems ?

**Comment by codykonior** [comment]
PS 5.1, throttle of 8, 500 jobs piped from start to wait to receive, and with a couple of these concurrently. It's not clear which part hangs on the source version (and it's only on some scenarios). 

I'll do some experimentation over the next week or so to try to pin it down but wanted to raise the issue first so it doesn't get put it as a release or something.

**Comment by MVKozlov** [comment]
Console hang or you can `Ctrl+C` it ?
or it's run from scheduler ?
you can also try my lates commit, it's have some problem fixed (for `remove-` and `stop-`)

**Comment by proxb** [comment]
Yea, it has been a busy few months for me with a new job and spending time with family. I'm tracking any new issues and PRs submitted as well as making some updates behind the scenes. 

I'm definitely curious as well as to what is going on and it looks like @MVKozlov has identified some key changes since 1.7.3.7 that could potentially be impacting the jobs. Looking forward to seeing what you find @codykonior in the coming weeks so we can identify and fix the bug.

**Comment by proxb** [comment]
On a side note, I will hold off on another release (and PowerShell Gallery update) until this is fixed. I will probably still accept the PR that is pending and then we can work backwards to the last known working commit to see what needs to be fixed.

**Comment by codykonior** [comment]
Yes I use strict mode for everything. Current version plus moving the dispose line seems to improve things but I'll check back in after an overnight run. This would imply this part is causing it to exit early and could stand to be improved:

```
If (($Data.Count -gt 0) -AND (-NOT ($Data.Count -eq 1 -AND $Null -eq $Data[0]))) {   
```

**Comment by MVKozlov** [comment]
Do you add `$DisposePoshRS_RunspacePools = $false` ? or current version means my fork latest version ?

**Comment by codykonior** [comment]
I did both suggestions - moving Dispose up a few lines plus setting this variable earlier.

**Comment by codykonior** [comment]
(On Boe's current checkins, not your fork)

**Comment by MVKozlov** [comment]
if so, try to move ` $job.Completed = $True ` back to current release place ;)

I think its  `$DisposePoshRS_RunspacePools = $false ` becase witout it strict mode fail and `$PoshRS_Jobs` cycle throws without exiting from `[Monitor]`

and if `Completed` also break things throwing can be in `If` you mentioned
anyway i think this code need `try {} finally {}` block

**Comment by codykonior** [comment]
Yes it seems to work with $job.Completed = $True in its version as per source control, meaning the earlier one was doing the most damage.

If it's possible $DisposePoshRS_RunspacePools is defined, test it with (Test-Path variable:DisposePoshRS_RunspacePools) in that if test. Best not to wrap in dummy try/catch.

**Comment by MVKozlov** [comment]
sorry, my English not so good, I can't understand half of you message :)
I can say only that `try finally` is not `try catch` :)

**Comment by codykonior** [comment]
It's possible it still exits in that section - just less frequently. I just had this happen.

Boe is it possible to merge the rest of the pull request so that I can then work on the one version?

**Comment by proxb** [comment]
Done. I'll wait to add it as a new release for a bit to see if this issue can be resolved.

**Comment by codykonior** [comment]
I haven't had any further issues in that build.
