### ISSUE TITLE
The first variable passed by -ArgumentList gets "lost"

### ISSUE THREAD

**Issue by iguy0** [proxb/PoshRSJob#144]
I believe I found an issue related to issue https://github.com/proxb/PoshRSJob/issues/132. I'm trying to pass 2 variables to a script block. The first variable passed by -ArgumentList gets "lost". Here is a sample replicable code. I went around it by adding an empty variable as my first variable.

$Test = {
param ($p1,$p2);
write-output "Argument $p1 and $p2 was passed"
}

$p1 = "Par1"
$p2 = "Par2"

Start-RSJob -Name TEST -ScriptBlock $Test -ArgumentList $p1, $p2

Start-RSJob -Name TEST -ScriptBlock $Test -ArgumentList '', $p1, $p2

Receive-RSJob -Name TEST

=============
Here is the result:

PS C:\Tools\PoshRSJob> $Test = {
>> param ($p1,$p2);
>> write-output "Argument $p1 and $p2 was passed"
>> }
>>
PS C:\Tools\PoshRSJob> $p1 = "Par1"
PS C:\Tools\PoshRSJob> $p2 = "Par2"
PS C:\Tools\PoshRSJob>
PS C:\Tools\PoshRSJob> Start-RSJob -Name TEST -ScriptBlock $Test -ArgumentList $p1, $p2

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
16       TEST                 Completed                    False        ...

PS C:\Tools\PoshRSJob>
PS C:\Tools\PoshRSJob> Start-RSJob -Name TEST -ScriptBlock $Test -ArgumentList '', $p1, $p2

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
17       TEST                 Completed                    False        ...

PS C:\Tools\PoshRSJob>
PS C:\Tools\PoshRSJob> Receive-RSJob -Name TEST
Argument Par2 and  was passed
Argument Par1 and Par2 was passed
PS C:\Tools\PoshRSJob>

Hope it helps.

**Comment by MVKozlov** [comment]
No, it's not lost, its go to $_ variable
``` powershell
$Test = {
 param ($p1,$p2);
 write-output "Argument psitem:$_ and p1:$p1 and p2:$p2 was passed"
}
```
I have long wanted to clarify this here #134

**Comment by singhkays** [comment]
Oh wow! I just spent a bunch of time trying to figure this out :( 

For now, I've removed the named parameters and resorted to using `$args[0], $args[1] ...`
