### ISSUE TITLE
Parallel file checking with RSJob

### ISSUE THREAD

**Issue by smwk** [proxb/PoshRSJob#150]
**Do you want to request a *feature* or report a *bug*?** Feature (I think)

**What is the current behavior?** I want to get the file version info from a file on aprox 20,000 computers on my domain. I have piped the computer DNSHostName into an RS-Job and it is working well except that it is taking some time. Maybe I'm misunderstanding but I thought PoshRSJob would run in parallel and potentially the whole script would only take as long as it takes on the slowest computer. It certainly works faster than the traditional checks but just wondering if I'm missing something?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?** Works as expected but not sure if fully running in parallel

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?** PS 4.0 on Windows Server 2012

**Please provide a code example showing the issue, if applicable:**
```PowerShell
#Code goes here
get-adcomputer -filter * | select -expand dnshostname | new-rsjob -scriptblock  { [System.Diagnostics.FileVersionInfo]::GetVersionInfo("\\$_\c$\somefile.txt").FileVersion } | wait-rsjob -showprogress | receive-rsjob | export-csv file.csv
```

**Comment by MVKozlov** [comment]
``` powershell
PS C:\> Get-Help Start-RSJob -Parameter Throttle

-Throttle <Int32>
    Number of concurrent running runspace jobs which are allowed at a time.

    Required?                    false
    Position?                    named
    Default value                5
    Accept pipeline input?       false
    Accept wildcard characters?  false
```
by default it just  **5**
but don't try to set Throttle = 20000, it will exhause all of your computer resource
and, because it executed on your computer, it can be limiter by max, simulateous network connections

**Comment by smwk** [comment]
Thanks for that, I set the throttle to 1000 and it made a dramatic difference. CPU and memory got maxed out for a while (2 core VMware, 8GB of memory) but it only took 40 minutes to run.
