### ISSUE TITLE
Rerun the failed jobs

### ISSUE THREAD

**Issue by sheldonhull** [proxb/PoshRSJob#154]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Failure is reported back (HasErrors)

I was wondering if anyone has implemented any type of basic "retry/rerun" on failed jobs? I have a loop inside that upon failure will retry, but if there is any way to easily implement in this project it would be great to know. For instance, if my sql connectivity fails, I want to retry the failed query automatically instead of just logging as error and closing job.

**Comment by proxb** [comment]
I'll have to dig into this one and see how difficult this might be to do. It feels like it may not be that hard, but I will need to do some research.

**Comment by DDog80sRocked** [comment]
@proxb Are you still working this issue?  I'm fairly new to using PoshRSJob but I successfully use it to reduce a job from 3.5 hours to 1.5 hours.  Unfortunately I still have a failed job here or there and wondered like @sheldonhull if there was a good way to restart a failed job or Catch a failure and retry?  Thanks.

**Comment by sheldonhull** [comment]
> @proxb Are you still working this issue? I'm fairly new to using PoshRSJob but I successfully use it to reduce a job from 3.5 hours to 1.5 hours. Unfortunately I still have a failed job here or there and wondered like @sheldonhull if there was a good way to restart a failed job or Catch a failure and retry? Thanks.

@DDog80sRocked try the powershell 7 `$Object | ForEach-Object -Parallel {}` and see if that helps. This doesn't have regular development (last master commit shows 2018), and I'd wager that with the advent of native parallel support this will further widen the gap in features that this great project filled in for. I'd guess this would be marked as an archived repo if @proxb reviews in within the next year or so as not sure the effort for bug fixes is worth it with that native parallel support.

Here's a quick snippet on my blog if you want another way to play around with it: [Show Parallel Output](https://www.sheldonhull.com/microblog/2020-06-17t22-32-32-00-00)

I'm closing this issue as I no longer require any help on this. Much appreciative of the project's help in the paste! 🎉🎉🎉
