### ISSUE TITLE
Pester/Appveyor Testing

### ISSUE THREAD

**Issue by proxb** [proxb/PoshRSJob#17]
At some point, it would be great to include some sort of testing.

**Comment by proxb** [comment]
Big thanks to @RamblingCookieMonster for his work in setting this up!

**Comment by RamblingCookieMonster** [comment]
Yikes - looks like I didn't consider implications of the PS2 tests!  Taking a peak at these.

**Comment by proxb** [comment]
Yea, I was just checking those out. No worries about it as this is so much further along with testing than what I would have gotten done. :)
It will be nice when I can do away with PS2 compatibility some day.
