### ISSUE TITLE
Verbose, warning and error streams

### ISSUE THREAD

**Issue by martin9700** [proxb/PoshRSJob#20]
I've noticed some of my jobs were having an error but nothing was coming back in the error stream.  Is it possible to get the above streams included with the Receive-RSJob?

**Comment by proxb** [comment]
I'll have to take a look at that and see if I can reproduce what you are seeing. If you happen to have something that I can quickly reproduce, that would definitely be helpful.

**Comment by martin9700** [comment]
Yes, I'll get something to you.  Sorry, crazy at work as usual!  Not sure I'd consider it a bug though, more a feature enhancement.

**Comment by proxb** [comment]
No worries about it! I can understand how busy things can get ;)
Cool, I will change it over to a Enhancement then. Thanks!

**Comment by martin9700** [comment]
Sorry for the gigantic delay, distracted at work!  Here's the sample code:

$TestJobs = ForEach ($Num in (1..5))
{
    Start-RSJob -ArgumentList $Num -ScriptBlock {
        Param (
            [int]$Number
        )
        Write-Verbose -Verbose -Message "This is test #$Number"
        Write-Error -Message "This is test #$Number"
    }
}

Write-Verbose -Verbose "There were $($TestJobs.Count) submitted, now waiting..."
$TestJobs | Wait-RSJob
$TestJobs | Receive-RSJob  #should see the verbose and error messages from above here
$TestJobs | Remove-RSJob

**Comment by martin9700** [comment]
With PSJobs, not only would I get the verbose and error streams, I can actually Try/Catch on the Receive-Job.

**Comment by jvedie** [comment]
I'm also facing the issue as I can't do any logging with Write-Verbose inside a RSJob which can be problematic for debugging.
Any idea about when this enhancement will be available ? It would be a huge plus.
Thanks for your work Boe.

**Comment by proxb** [comment]
This is still on my radar, but I just haven't had the necessary time to dedicate myself to looking at this yet. I'll keep everyone posted on what I can find.

**Comment by proxb** [comment]
I think this one is going to be more challenging to accomplish (without changing the current framework of the project) as we won't be able to see the streams until we call EndInvoke() at the very end when the job has finished and at that point all of the data comes rolling out. The best that I have currently is that the streams (except for output) are available in the RSJob object under their respective properties. I'll keep digging though and see if I can figure something else out.

**Comment by martin9700** [comment]
For me, just emulating the PSJob behavior of having all of the streams come out as one when the Retrieve-RSJob is run would be fine (not sure if that's what you meant by the EndInvoke()).  

Have properties available would work as an interim step.

**Comment by proxb** [comment]
Correct. The way it currently works is that there is a background runspace handling all of the completed RSJobs by calling EndInvoke() on them which pulls in the output stream. This is used to determine if there is data available in the RSJob (HasMoreData property). I'm looking for another way to determine if there is output available other than just calling EndInvoke() which would help to keep the streams available when calling Receive-RSJob, but so far have not been too successful.

If you look at the current RSJob object, I have all of the streams available (Verbose, Error, Warning, Progress) that you can look at while the job is running as well as when it has finished.

**Comment by martin9700** [comment]
I guess a poor mans approach would be to put a simple loop in the Retrieve-RSJob that "If (verbose) {$this.VerboseStream}" type of thing (excuse the pseudo-code)

**Comment by proxb** [comment]
Exactly. It's definitely a workaround at the moment, but as long as new bugs don't show up, I am going to spend some more time with this and see what I can make happen.

**Comment by dmellenbruch** [comment]
This caused issues for me as well, but I implemented a workaround using the code below.
    if ($_.HasErrors) {
        $_ | select -ExpandProperty Error | % { throw $_ }
    }
    else {
        $_.Output
    }

**Comment by proxb** [comment]
@martin9700 Would you consider this one closed after implementing your updates? Or would you like to see it more in line with PSJobs?

**Comment by martin9700** [comment]
I think it's closed.

**Comment by sheldonhull** [comment]
This should be tagged as wiki material :-)

**Comment by jrob24** [comment]
Can someone please provide some same code of this error handling in use? I am struggling trying to figure out how to use it. Thank you!
