### ISSUE TITLE
Error using Start-RSJob

### ISSUE THREAD

**Issue by bab5470** [proxb/PoshRSJob#29]
I'm trying to use Start-RSJob to kick off some code in parallel:

```
		Start-RSJob -Name {$($backup.Name)} -Throttle 2 -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup -ScriptBlock {
            
			# Create a unique log file for this particular backup job
			$log="$ScriptDir\logs\corebackup\$ScriptName $($backup.Name) $DateStamp.log"
			
			# Begin the Backup
			BeginBackup $backup.Name $log
			
			# Backup the mssql database
			MSSQLBackup $backup.Name $backup.DBPath 
				
			# Backup the files
			FilesBackup $backup.Name $backup.FolderName $backup.FilesPath 

			# End the Backup
			EndBackup $backup.FolderName $backup.Name $log $emailTo
        }
		
		Get-RSjob | Receive-RSJob
```

When I do though I get the following errors:

```
WARNING: BeginBackup: Cannot find path 'Function:\BeginBackup' because it does not exist.
WARNING: MSSQLBackup: Cannot find path 'Function:\MSSQLBackup' because it does not exist.
WARNING: FilesBackup: Cannot find path 'Function:\FilesBackup' because it does not exist.
WARNING: EndBackup: Cannot find path 'Function:\EndBackup' because it does not exist.

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
11                            NotStarted      False        False        ...
WARNING: BeginBackup: Cannot find path 'Function:\BeginBackup' because it does not exist.
WARNING: MSSQLBackup: Cannot find path 'Function:\MSSQLBackup' because it does not exist.
WARNING: FilesBackup: Cannot find path 'Function:\FilesBackup' because it does not exist.
WARNING: EndBackup: Cannot find path 'Function:\EndBackup' because it does not exist.
12                            NotStarted      False        False        ...
WARNING: BeginBackup: Cannot find path 'Function:\BeginBackup' because it does not exist.
WARNING: MSSQLBackup: Cannot find path 'Function:\MSSQLBackup' because it does not exist.
WARNING: FilesBackup: Cannot find path 'Function:\FilesBackup' because it does not exist.
WARNING: EndBackup: Cannot find path 'Function:\EndBackup' because it does not exist.
13                            NotStarted      False        False        ...
```

There seems to be two issues - one it can't find the functions (which are defined above where I am calling this code) and two its not starting the jobs?

Is my syntax wrong?

Thanks
Brad

**Comment by proxb** [comment]
The throttle is the maximum number of concurrent jobs that are allowed to run at a time. The way you are running it now means that it will only run 1 job with a throttle of 2 max jobs. I don't see in your code where you would be starting 2 jobs.

You have a few variables defined in the scriptblock, but those won't make it through unless you use $Using: to ensure the variables in the parent scope are brought into the scope of the scriptblock. Something like this:

```PowerShell
Start-RSJob -Name {$($backup.Name)} -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup -ScriptBlock {

    # Create a unique log file for this particular backup job
    $log="$Using:ScriptDir\logs\corebackup\$Using:ScriptName $($Using:backup.Name) $Using:DateStamp.log"

    # Begin the Backup
    BeginBackup $Using:backup.Name $log

    # Backup the mssql database
    MSSQLBackup $Using:backup.Name $Using:backup.DBPath 

    # Backup the files
    FilesBackup $Using:backup.Name $Using:backup.FolderName $Using:backup.FilesPath 

    # End the Backup
    EndBackup $Using:backup.FolderName $Using:backup.Name $log $Using:emailTo
}

Get-RSjob | Receive-RSJob
```

Are your custom functions currently defined in the console? By that I mean could you currently use them? If you try to get the content of the function...

```PowerShell
Get-Content Function:\BeginBackup
```

...It should show you the source code. If not, then they should be made available first.

**Comment by bab5470** [comment]
**The throttle is the maximum number of concurrent jobs that are allowed to run at a time. The way you are running it now means that it will only run 1 job with a throttle of 2 max jobs. I don't see in your code where you would be starting 2 jobs.**

There is a foreach loop above the block which i didn't post. It iterates through entries in an xml config file.

**You have a few variables defined in the scriptblock, but those won't make it through unless you use $Using: to ensure the variables in the parent scope are brought into the scope of the scriptblock. Something like this:**

Perfect I've fixed that.

**Are your custom functions currently defined in the console? By that I mean could you currently use them? If you try to get the content of the function...**

The functions are defined above the script block - I'm not sure if that's what you mean?

Similar to Using: do I need to preface the functions with function: ?

Thanks
Brad

**Comment by proxb** [comment]
I wouldn't use a ForEach loop with Start-RSJob; it is designed to accept input directory from the pipeline vs. using a loop. This is how it is able to throttle the jobs as it uses a single runspacepool.

When I ask about the functions being defined, that means that they are loaded in the console so they could be used. In the scriptblock, they are being called, but are not loaded. If you run the following in your current console...

```PowerShell
Get-ChildItem Function:\
```
...Do you see the functions listed in the console? If not, then they are not actually loaded in the console and won't be picked up as a function to load when calling Start-RSJob.

Here is a quick example of what I am talking about:
```PowerShell
Function Double {Param([parameter(ValueFromPipeline)][int]$i)Process{$i*2}}
1..5 | Start-RSJob -Name {$_} -ScriptBlock {
    [pscustomobject]@{
        Value = $_|Double
    }    
} -FunctionsToLoad Double | 
Wait-RSJob | Receive-RSJob
```

**Comment by bab5470** [comment]
**I wouldn't use a ForEach loop with Start-RSJob; it is designed to accept input directory from the pipeline vs. using a loop. This is how it is able to throttle the jobs as it uses a single runspacepool.**

I think I have to have a for each loop so that I can iterate through elements/entries in an xml config file. I'm not sure how I'd pipeline that in? See below:

```
if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {
	foreach ($backup in $xmlfile.configuration.DBAndFilesBackup.MSSQL.backup) {		
		
		#Invoke-Parallel -ImportVariables -Throttle 2 {
		Start-RSJob -Name {$($backup.Name)} -Throttle 2  -ScriptBlock {
            
			# Create a unique log file for this particular backup job
			$log="$Using:ScriptDir\logs\corebackup\$Using:ScriptName $($Using:backup.Name) $Using:DateStamp.log"
			
			# Begin the Backup
			BeginBackup $Using:backup.Name $log
			
			# Backup the mssql database
			MSSQLBackup $Using:backup.Name $Using:backup.DBPath 
				
			# Backup the files
			FilesBackup $Using:backup.Name $Using:backup.FolderName $Using:backup.FilesPath 

			# End the Backup
			EndBackup $Using:backup.FolderName $Using:backup.Name $log $Using:emailTo
        } -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup | Wait-RSJob | Receive-RSJob
		
		
	}
}
```

**If you run the following in your current console... Get-ChildItem Function:\ Do you see the functions listed in the console**

No I don't - but they are defined at the beginning of the script (before calling Start-RSJob) Is that not sufficient? If not, how do I load the functions in the console? Create a POSH module?


Also with using "$Using: I'm getting this error for just one of my variables:
$Using:ScriptDir is not a valid Using: variable!
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\POSHRSJob\PoshRSJob.psm1:219 char:13
+             Throw "$($Var.SubExpression.Extent.Text) is not a valid Using: varia ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ($Using:ScriptDi...sing: variable!:String) [], RuntimeException
    + FullyQualifiedErrorId : $Using:ScriptDir is not a valid Using: variable!

I see $ScriptDir defined at the top of my script though: 
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

**Comment by proxb** [comment]
With that example, this is how I would run the script:

```PowerShell
if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {
    $xmlfile.configuration.DBAndFilesBackup.MSSQL.backup | 
    Start-RSJob -Name {$_.Name} -Throttle 2  -ScriptBlock {

        # Create a unique log file for this particular backup job
        $log="$Using:ScriptDir\logs\corebackup\$Using:ScriptName $($_.Name) $Using:DateStamp.log"

        # Begin the Backup
        BeginBackup $_.Name $log

        # Backup the mssql database
        MSSQLBackup $_.Name $_.DBPath 

        # Backup the files
        FilesBackup $_.Name $_.FolderName $_.FilesPath 

        # End the Backup
        EndBackup $_.FolderName $_.Name $log $Using:emailTo
    } -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup | Wait-RSJob | Receive-RSJob
}
```

I'll need to do some testing running this in a script to see if I can duplicate some of the other errors such as the function loading and that $Using: issue. You could add... 
```PowerShell
Write-Verbose "ScriptDir: $($ScriptDir)" -Verbose
```
...to verify that it has a value. Typically that error with $Using:Scriptdir means that it couldn't find a variable with that name/value.

**Comment by proxb** [comment]
Ok, I was able to duplicate the $Using:ScriptDir error that you are seeing. I'll dig more into it to see what is going on and get it fixed.

**Comment by proxb** [comment]
This is definitely a scoping issue with the accessing the variables and functions that are defined in a script. As a workaround you will need to assign those in the Global scope until I can figure out a fix for this. At the end of the script, just be sure to remove the functions/variables which were globally defined. Here is an example:

```PowerShell
Function global:BeginBackup{}
Function global:MSSQLBackup{}
Function global:FilesBackup{}
Function global:EndBackup{}
$Global:ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {
    $xmlfile.configuration.DBAndFilesBackup.MSSQL.backup | 
    Start-RSJob -Name {$_.Name} -Throttle 2  -ScriptBlock {

        # Create a unique log file for this particular backup job
        $log="$Using:ScriptDir\logs\corebackup\$Using:ScriptName $($_.Name) $Using:DateStamp.log"

        # Begin the Backup
        BeginBackup $_.Name $log

        # Backup the mssql database
        MSSQLBackup $_.Name $_.DBPath 

        # Backup the files
        FilesBackup $_.Name $_.FolderName $_.FilesPath 

        # End the Backup
        EndBackup $_.FolderName $_.Name $log $Using:emailTo
    } -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup | Wait-RSJob | Receive-RSJob
}
Remove-Item Function:\BeginBackup
Remove-Item Function:\MSSQLBackup
Remove-Item Function:\FilesBackup
Remove-Item Function:\EndBackup
Remove-Variable Something -Scope Global
```

**Comment by bab5470** [comment]
I'm not sure if this is related to the issue above, but I can't get powershell transcription (logging) working. Should transcription work? (It doesn't work with the native start-job commandlet - which is why I'm using POSHRSJob to begin with - http://stackoverflow.com/questions/3835997/start-transcript-causes-script-to-fail-in-a-background-job)

Here's what I'm doing:

```
#######################################################################
# BEGIN BACKUP
#######################################################################
Function global:BeginBackup ($BackupName, $log) { 
		
		# Start a transcript (log) of script execution
		Start-Transcript $log -force
		
		# Print a header containing the server name
		PrintHeader $BackupName.toUpper()
		
		# Starting Backup
		Write-Host $(get-date) "STARTED: Processing $($BackupName)"
}


if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {

	$xmlfile.configuration.DBAndFilesBackup.MSSQL.backup | 
	Start-RSJob -Name {$_.Name} -Throttle 2  -ScriptBlock {

			# Create a unique log file for this particular backup job
			$log="c:\ourlocation\scripts\logs\corebackup\corebackup $($_.Name) 8-20-2015.log"
			
			# Begin the Backup
			BeginBackup $_.Name $log

	}  -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup,Mailer,PrintHeader | Wait-RSJob | Receive-RSJob
}
```

Note the transcription is triggered in the begin backup function. However I'm not seeing the log file being created. I thought at first that it might be due to the variables in the $log value not being defined so hard coded the path - but the log still isn't being created. 

There's also a EndBackup function which I didn't include here for brevity that obviously stops the transcription.

Thanks
Brad

**Comment by proxb** [comment]
Hmm.. I haven't tried the start-transcript against PoshRSJob but can certainly test it. I did upload a new version that should have a fix for the variable issue. Fixing the Functions that are loaded in the script vs. in the console is going to be a little more challenging to figure out.

**Comment by bab5470** [comment]
Any thoughts on transcription?

Thanks
Brad

**Comment by proxb** [comment]
Seems to work fine with the RSJob. But I haven't tested with the call to Start-Transcript in a custom function.

![rsjob_transcript](https://cloud.githubusercontent.com/assets/5827856/9431813/348233d4-49de-11e5-8562-55f9cd165601.png)

**Comment by bab5470** [comment]
I'm not sure what I'm doing differently but I'm not getting transcription working. Here's what I setup as a test:

```

# MSSQL & FILES
if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {

	$xmlfile.configuration.DBAndFilesBackup.MSSQL.backup | 
	Start-RSJob -Name {$_.Name} -Throttle 2  -ScriptBlock {

			# Create a unique log file for this particular backup job
			$log="$Using:ScriptDir\logs\corebackup\$Using:ScriptName $($_.Name) $Using:DateStamp.log"

        	# Start a transcript (log) of script execution
		    Start-Transcript -Path c:\$_.Name.txt -force			

            Write-Host "Foo"

            Stop-Transcript

	} -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup,Mailer,PrintHeader | Wait-RSJob | Receive-RSJob
}

```

Yet I run the script go check my c drive and I don't see a file created there named (backup name.).txt?

Thanks,
Brad

**Comment by bab5470** [comment]
Here's what I get running the same code as above:

![2015-08-24_13-10-35](https://cloud.githubusercontent.com/assets/8186104/9446848/eaa783a2-4a61-11e5-9f3e-3958b01e3fb1.jpg)

**Comment by bab5470** [comment]
Actually just noticed the HasErrors was set to true. So doing this

PS C:\Users\brad.baker> Get-RSJob -Id 1 | Select *

```

HasErrors      : True
Verbose        :
Debug          :
Warning        :
Progress       :
Name           : Job1
ID             : 1
State          : Completed
InstanceID     : 21ab0725-9dfe-488d-bc92-3e5c3f2c73c8
Handle         : System.Management.Automation.PowerShellAsyncResult
Runspace       :
InnerJob       : System.Management.Automation.PowerShell
Finished       :
Command        :  Start-Transcript -Path C:\asdf\asdf.txt -Force; Write-Host "Foo"; Stop-Transcript
Error          : {This host does not support transcription., A command that prompts the user failed because the host
                 program or the command type does not support user interaction. Try a host program that supports user
                 interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove
                 prompt-related commands from command types that do not support user interaction, such as Windows
                 PowerShell workflows., This host does not support transcription.}
HasMoreData    : False
Output         :
RunspacePoolID : 59c0536f-e5b0-4cf8-a513-fec719f1752c
Completed      : True

```

So how come this works for you but not me? :)

**Comment by bab5470** [comment]
I'm running powershell version 3 on windows 2008 R2:

```
PS C:\Users\brad.baker> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1
```

**Comment by proxb** [comment]
Interesting...
I tested on PowerShell V5 but will do some testing against V3/4 to see what happens.

**Comment by bab5470** [comment]
So I've mostly been able to work around this by changing:

```
Write-Host $value
```

To:

```
Write-Output
```

then using:

```
| Wait-RSJob | Receive-RSJob | Out-file "$ScriptDir\logs\$ScriptName $($backup.Name) $DateStamp.log"
```

Its no longer using transcription but its logging none the less. 

The issue I am having though is that $backup.Name isn't being populated. Is there some way I can grab that value from the scriptblock?

**Comment by proxb** [comment]
I'm not aware of a way to get the $Backup.Name from the scriptblock unless it is specified as a $Global:Backup variable...but based on the code that changes with each iteration so you would only end up with the log containing the last backup name that was used.

**Comment by bab5470** [comment]
I think you've summed up the issue. I just can't think of a way to work around it :(

**Comment by proxb** [comment]
You will probably have to mix in your Write-Output and piping to Out-File and appending the output within the function or scriptblock to get it writing to a log file for each backup.

**Comment by bab5470** [comment]
Are you sure the $Using issue has been fixed? I'm using the following code:

```
# MSSQL & FILES
if ($xmlfile.configuration.DBAndFilesBackup.item("MSSQL").haschildnodes) {
	$xmlfile.configuration.DBAndFilesBackup.MSSQL.backup | 
	ForEach-Object {
		$BackupName = $_.Name
		$_ | Start-RSJob -Name {$_.Name} -Throttle 2  -ScriptBlock {
		
			# Begin the Backup
			BeginBackup $_.Name $log
	
			Write-Output "Backup Dir" $Using:backupdir
			Write-Output "Backup Temp Dir" $Using:backuptempdir
		
			# Backup the mssql database
			MSSQLBackup $_.Name $_.DBPath $backupdir $backuptempdir

			# Backup the files
			FilesBackup $_.Name $_.FolderName $_.FilesPath $backupdir $backuptempdir

			# End the Backup
			EndBackup $_.FolderName $_.Name $log $emailTo $backupdir $backuptempdir

		} -FunctionsToLoad BeginBackup,MSSQLBackup,FilesBackup,EndBackup,Mailer,PrintHeader | 
			Get-RSJob|
				Wait-RSJob | 
					Receive-RSJob | 
						Out-file "$ScriptDir\logs\corebackup\$ScriptName $BackupName $DateStamp.log"
	}
}
```

When I check the output I see:

```
Backup Dir
Backup Temp Dir
```

Which should read

```
Backup Dir C:\backups\
Backup Temp Dir C:\temp
```

I've tried it by making the variables global, not global, using $Using and not, I don't seem to be able to get the variables to populate! Again I'm using powershell 3 on windows 2008 - in case that makes a difference.

**Comment by proxb** [comment]
I'm pretty sure its fixed. Looking at your code, I do not see $backuptempdir and $backupdir being declared anywhere in the script prior to the Start-RSJob call. There is a new bug that was introduced by the fix that didn't halt the starting of the RSJob if a $Using: variable didn't exist and instead continues with the job creation. I've fixed the bug already but cannot get it uploaded until later tonight.

**Comment by bab5470** [comment]
Above the block I posted I have:

```
# Path for backups
$backupdir = "C:\backups"

# Temp folder for backups in progress
$backuptempdir = "C:\temp"

# Email Addresses for Report
$emailTo = "me@mydomain.com" 
```

Again I've also tried

```
# Path for backups
$Global:backupdir = "C:\backups"

# Temp folder for backups in progress
$Global:backuptempdir = "C:\temp"

# Email Addresses for Report
$Global:emailTo = "me@mydomain.com" 
```

In either situation Write-Output is not spitting out any values - its like the variables are nulls/empty.

**Comment by proxb** [comment]
Add -Verbose to Start-RSJob and post back the results of the verbose output for me.

**Comment by bab5470** [comment]
```
VERBOSE: Creating runspacepool <f2205d18-6656-4745-a0e8-5976a7e972ab> with max threads: 2
VERBOSE: Will use $_ in Param() Block
VERBOSE: Found 2 $Using: variables!
VERBOSE: Using System.Xml.XmlElement as pipline variable
VERBOSE: Adding Param: $Using:backupdir Value:
VERBOSE: Adding Param: $Using:backuptempdir Value:
VERBOSE: Creating runspacepool <6fc8bce5-4916-4a69-9905-9be231876ef9> with max threads: 2
VERBOSE: Will use $_ in Param() Block
VERBOSE: Found 2 $Using: variables!
VERBOSE: Using System.Xml.XmlElement as pipline variable
VERBOSE: Adding Param: $Using:backupdir Value:
VERBOSE: Adding Param: $Using:backuptempdir Value:
```

**Comment by proxb** [comment]
What does `$ErrorActionPreference` look like? Just want to make sure that it is set to 'Continue'.

**Comment by bab5470** [comment]
It is set to continue.

**Comment by proxb** [comment]
Once I get this module update pushed out, I want you to try running the code again to see what happens. It won't be until later this evening though.

**Comment by proxb** [comment]
I just updated the module to fix a few things, go ahead and give it a shot when you get time and let me know how it works now.

**Comment by bab5470** [comment]
That fixed the variable issue.... now if I can figure out how to output to a log in a reasonable manner.

**Comment by proxb** [comment]
That's good to hear (the variable issue being resolved) and I am still looking to fix the issue with the functions not loaded without being Global.

**Comment by bab5470** [comment]
I've ended up ditching transcription and simply doing "| Write-Output | Out-file $log -Append" after everything I need to log. 

Its a bit of an ugly hack but I just can't get transcription to work with parallelism and I need both. Doing jobs one by one (serially) isn't going to work and I have to have some log of what's happening.

If you could fix the issue with functions not having to be global that would be great - but its not a huge deal to make them global and then just removing them at the end of the script.
