### ISSUE TITLE
Readme.md doesn't reference: Latest Updates to PoshRSJob

### ISSUE THREAD

**Issue by vercellone** [proxb/PoshRSJob#30]
The README.md references [Introducing PoshRSJob as an Alternative to PowerShell Jobs](http://learn-powershell.net/2015/03/31/introducing-poshrsjob-as-an-alternative-to-powershell-jobs/) for more information and examples, but neither location mentions [Latest Updates to PoshRSJob](http://learn-powershell.net/2015/04/19/latest-updates-to-poshrsjob/).

This tripped me up when I tried to use -ArgumentList and a Param() block based on your [initial post](http://learn-powershell.net/2015/03/31/introducing-poshrsjob-as-an-alternative-to-powershell-jobs/).  In hindsight, $Using with no Param() block makes more sense.  But, it would be helpful to newcomers to highlight the updates.

**Comment by proxb** [comment]
Thanks for the heads up I've updated the ReadMe to reference my more recent post highlighting the new features of PoshRSJob.
