### ISSUE TITLE
Zero not passed in the pipeline

### ISSUE THREAD

**Issue by mg07647** [proxb/PoshRSJob#31]
This code only returns four values...the zero is missing. Is this a bug or my understanding of the input pipeline?
-2..2 | Start-RSJob -ScriptBlock {$_} | Wait-RSJob | Receive-RSJob
-2
-1
1
2

**Comment by proxb** [comment]
Weird. I will have to look into that as that really shouldn't be happening.

**Comment by proxb** [comment]
Think that I have this one figured out and will update the module later tonight.

**Comment by proxb** [comment]
Download the latest version and give it a run. It should work fine now.

**Comment by mg07647** [comment]
Fixed - Thanks!
