### ISSUE TITLE
Display Verbose Stream when Jobs are Received

### ISSUE THREAD

**Issue by ryan-leap** [proxb/PoshRSJob#47]
Would it be possible to display verbose stream (when Write-Verbose is used in the script block being executed within a job) messages when RSJobs are received?  Traditional PSJobs do display the verbose stream if the $VerbosePreference variable is set to something other than SilentlyContinue within the script block but I'm not seeing verbose output with RSJobs.

**Comment by proxb** [comment]
Can you put together some demo code showing this so I can look at and then work to see if I can make a fix for this?

**Comment by proxb** [comment]
Duplicate of #20
