### ISSUE TITLE
Param() not being populated with data from pipeline

### ISSUE THREAD

**Issue by proxb** [proxb/PoshRSJob#56]
From http://stackoverflow.com/questions/34639565/powershell-threading-help-using-poshrsjob-module/34646786#34646786

When you specify a Param() with a single parameter, it should take on the value of the data coming in from the pipeline but doesn't.

```PowerShell
@('12.34.56.78')|Start-RSJob -Name {"TEST_$($_)"} -ScriptBlock {
    Param($Computername)
    Test-Connection -ComputerName $Computername -Quiet
}

get-RSJob|Receive-RSJob
```

**Comment by martin9700** [comment]
This would be pretty tricky, I would think.  What if you pass it an object?  Or an integer?  

Tested with Start-Job and it DOES works for strings (didn't test an integer) but does not work for objects.

**Comment by proxb** [comment]
I was able to get this working again and will be available in the next update.
