### ISSUE TITLE
Minor receive-rsjob incompatibility with receive-job - doesn't accept RSJob variable 

### ISSUE THREAD

**Issue by ALuckyGuy** [proxb/PoshRSJob#61]
With standard PS jobs, you can do the following:

    $job = Start-Job ...
    receive-job $job

If you do the same with PoshRSJobs:

    $job = Start-RSJob ...
    receive-RSJob $job

the following error is produced by receive-rsjob:

    Receive-RSJob : A positional parameter cannot be found that accepts argument 'PoshRS.PowerShell.RSJob'.

Additionally if you try the following

    receive-rsjob -job $job

no output is received. This works however:

    $job | receive-rsjob

as does this:

    receive-rsjob -ID $job.id

**Comment by proxb** [comment]
The latest update should resolve this. Can you test and verify for me?

**Comment by ALuckyGuy** [comment]
Will do

**Comment by ALuckyGuy** [comment]
This is fixed.
