### ISSUE TITLE
InnerJob.HadErrors doesn't exist in PowerShell v2

### ISSUE THREAD

**Issue by ALuckyGuy** [proxb/PoshRSJob#64]
In PoshRSJob.Types.ps1xml, the following reference to HadErrors is invalid:

    <Types>
      <Type>
        <Name>PoshRS.PowerShell.RSJob</Name>
        <Members>
          <ScriptProperty>
            <Name>HasErrors</Name>
            <GetScriptBlock>
              $this.innerjob.HadErrors
            </GetScriptBlock>
          </ScriptProperty>
        </Members>
      </Type>

Unfortunately, HadErrors wasn't introduced until v3 - [System.Management.Automation.PowerShell](https://msdn.microsoft.com/en-us/library/system.management.automation.powershell_members(v=vs.85).aspx)

There reference causes the following error: 
    Property 'HadErrors' cannot be found on this object. Make sure that it exists.

**Comment by proxb** [comment]
That's unfortunate. I guess I'll throw in a try/catch to handle that issue.

**Comment by ALuckyGuy** [comment]
Not sure if it's the best way but this seems to work:

  <Type>
    <Name>PoshRS.PowerShell.RSJob</Name>
    <Members>
      <ScriptProperty>
        <Name>HasErrors</Name>
        <GetScriptBlock>
           if ($psversiontable.psversion.major -ge 3){ 
              $this.innerjob.HadErrors 
           }else{ 
              ($this.innerjob.Streams.Error -ne $null)
           }
        </GetScriptBlock>
      </ScriptProperty>
    </Members>
  </Type>

**Comment by proxb** [comment]
The latest update should resolve this. Can you test and verify for me?

**Comment by ALuckyGuy** [comment]
I'll take a look at it and get back with you.

**Comment by ALuckyGuy** [comment]
This seems to be working.Closing it.
