### ISSUE TITLE
Bug with v2 variable substitution - single-quoted strings get $var references replaced

### ISSUE THREAD

**Issue by ALuckyGuy** [proxb/PoshRSJob#65]
Try the following running PowerShell -version 2:

    1..2|start-rsjob -Name {$_} -ScriptBlock {
            $var = 'this value'
            new-object psobject -Property @{
                Result=($_)
                Test='Confirming $var is not substituted'
                Something="Confirming $var is substituted"
            }
    }            
    Get-RSjob | Receive-RSJob

v2 produces this result:

    Result Something                            Test                                    
    ------ ---------                            ----                                    
         1 Confirming this value is substituted Confirming this value is not substituted
         2 Confirming this value is substituted Confirming this value is not substituted

v3 & later produces correct results:

    Result Something                            Test                                    
    ------ ---------                            ----                                    
         1 Confirming this value is substituted Confirming $var is not substituted
         2 Confirming this value is substituted Confirming $var is not substituted

**Comment by ALuckyGuy** [comment]
I believe I have a fix for this. Might be a more elegant way to do it, but it works.

The problem is in the ConvertScriptBlockV2 function and the fact that it always added strings to the built script using double-quotes. Instead the string needs to be re-added to the script using the same quoting as the source.

This code:

            'String' {
                [void]$StringBuilder.Append(("`"{0}`"" -f $Tokens[$i].Content))
            }

can be changed to:

            'String' {
                $qchar = $ScriptBlock.ToString().Split("`n")[($Tokens[$i].StartLine-1)].Substring($Tokens[$i].StartColumn-1,1)
                [void]$StringBuilder.Append(("{0}{1}{0}" -f $qchar,$Tokens[$i].Content))
            }

This fixes the problem I demonstrated above but I don't really have experience with the parser and haven't tested with "here" strings.

**Comment by proxb** [comment]
Great! I'll incorporate that and give it a run to test it. Hopefully I can include this as well as a couple of other things in an update later this week/weekend.

**Comment by proxb** [comment]
I tested the fix action and it seems to work. I'll include it in the next update.

**Comment by proxb** [comment]
This one should be fixed in the latest release

**Comment by ALuckyGuy** [comment]
Yep, corrected.
