### ISSUE TITLE
Parameters don't work with PowerShell v2

### ISSUE THREAD

**Issue by ALuckyGuy** [proxb/PoshRSJob#66]
Try the following script:

    1..2|start-rsjob -Name {$_} -ScriptBlock {
    param($parm)
            new-object psobject -Property @{
                Result=($parm)
            }
    }            
    Get-RSjob | Receive-RSJob

With v3 & later, produces the following:

     Result
     ------
          1
          2

With v2 (run with PowerShell -version 2), the output is blank.

     Result
     ------

**Comment by ALuckyGuy** [comment]
This problem seems to be with Start-RSJob and how PowerShell v2 deals with references to the count property on $null parameters: $null.count returns 0 in v3 and later but in v2 it returns nothing.

So, in Start-RSJob.ps1 if you change the two references to **$ArgumentList.count** to **($ArgumentList) -and $ArgumentList.count**, the example I gave in the OP works in v2 and later: 

        $SBParamCount = @(GetParamVariable -ScriptBlock $ScriptBlock).Count
        If ($PSBoundParameters.ContainsKey('InputObject')) {
            If ($ArgumentList.Count -gt 0) {
                $SBParamCount++
            } Else {
                $SBParamCount--
            }
        }
        If ($ArgumentList.Count -ne $SBParamCount -AND $IsPipeline) {
            Write-Verbose 'Will use $_ in Param() Block'
            $Script:Add_ = $True
        } Else {
            $Script:Add_ = $False
        }

to:

        $SBParamCount = @(GetParamVariable -ScriptBlock $ScriptBlock).Count
        If ($PSBoundParameters.ContainsKey('InputObject')) {
            If ( ($ArgumentList) -and $ArgumentList.count -gt 0) {
                $SBParamCount++
            } Else {
                $SBParamCount--
            }
        }
        If ( ($ArgumentList) -and $ArgumentList.count -ne $SBParamCount -AND $IsPipeline) {
            Write-Verbose 'Will use $_ in Param() Block'
            $Script:Add_ = $True
        } Else {
            $Script:Add_ = $False
        }

**Comment by proxb** [comment]
Great! I appreciate the reports that you have been providing. It definitely helps to make this module better for everyone!

**Comment by proxb** [comment]
This one appears to break the following attempt with a single item:

```PowerShell
1|Start-RSJob -ScriptBlock {$_}
```

In which there appears to be no data being received.

**Comment by proxb** [comment]
Made some adjustments and it appears to be working now with the new version that I am working on.

**Comment by proxb** [comment]
This one should be fixed in the latest release

**Comment by ALuckyGuy** [comment]
This looks good for my tests as well. Closing it.
