### ISSUE TITLE
Get-RSJob state complete before job is complete

### ISSUE THREAD

**Issue by bushe** [proxb/PoshRSJob#7]
Get-RSJob is sometimes reporting that the job is complete before the job is actually complete. I started 16 jobs and run a do while until all jobs equal completed. All my jobs return a PSObject at the end, sometimes 1 or 2 jobs will report that they are completed, but HasMoreData is false; waiting a few seconds later reports that HasMoreData is true.

**Comment by proxb** [comment]
I think that I have this issue tracked down and fixed. I'll update the repo later tonight.
