### ISSUE TITLE
Properties of Get-GPO object from pipeline not passing into job

### ISSUE THREAD

**Issue by cwhits** [proxb/PoshRSJob#70]
What am I doing wrong here? Why are the properties not passing into the job?
```powershell
$AllGPOs = Get-GPO -All | Sort-Object DisplayName
$AllGPOs[0..4] | Start-RSJob  -ScriptBlock { 
    [pscustomobject]@{
    DisplayName  = $_.DisplayName
    GpoStatus    = $_.GpoStatus
    Owner        = $_.Owner
    CreationTime = $_.CreationTime
    Id           = $_.id
    }
} | Wait-RSJob | Receive-RSJob
```

The objects that come back only have the ID populated. However, doing it _not_ as a job works.

```powershell
$AllGPOs[0..4] | % { [pscustomobject]@{
    DisplayName  = $_.DisplayName
    GpoStatus    = $_.GpoStatus
    Owner        = $_.Owner
    CreationTime = $_.CreationTime
    Id           = $_.Id
    }        
}
```

**Comment by cwhits** [comment]
It appears that other objects go just fine. Get-Process and Get-AdComputer both pass all their properties.

**Comment by proxb** [comment]
That's weird. It's probably some quirkiness with that particular cmdlet. I'll check this out tomorrow and see if I can reproduce the issue and maybe see why it is happening.

**Comment by proxb** [comment]
It looks like it was what I suspected. Similar to some of the ActiveDirectory module commands, you will have to pipe your results to Select * to ensure that the data is passed correctly to an RSJob.

```PowerShell
$AllGPOs[0..4] | Select * | Start-RSJob  -ScriptBlock {
     [pscustomobject]@{
     DisplayName  = $_.DisplayName
     GpoStatus    = $_.GpoStatus
     Owner        = $_.Owner
     CreationTime = $_.CreationTime
     Id           = $_.id
     }
 }  | Wait-RSJob | Receive-RSJob
```

When I did that, everything worked as expected. Without doing that, I saw the same issue with the lack of properties being displayed.

**Comment by proxb** [comment]
@cwhits Have you had a chance to look a this again with my suggestion?

**Comment by cwhits** [comment]
Yep. That works.
