### ISSUE TITLE
Jobs don't have output when using ADSI WinNT provider (Receive-RSJob)

### ISSUE THREAD

**Issue by kborowinski** [proxb/PoshRSJob#76]
I've found interesting case when Receive-RSJob has no output when using ADSI provider inside script block. Following New-LocalUser function creates local user account on local or remote computer(s) using Start-RSJob . Function behaves as expected when ADSI provider can't connect to the specified computer and returns custom PSObject. However when user account is created successfully, Receive-RSJob has no output.

Expected behavior (computer doesn't exists):
```
PS C:\> New-LocalUser -ComputerName 'DoesNotExist' -UserName 'Test' -Password '123456789'

Computer     User Success
--------     ---- -------
DoesNotExist Test   False

PS C:\>
``` 

Unexpected behavior (user account is created but Receive-RSJob does not return custom PSObject)

```
PS C:\> New-LocalUser -ComputerName 'localhost' -UserName 'Test' -Password '123456789'
PS C:\>
```

```
#requires -Version 3 -Modules PoshRSJob
Set-StrictMode -Version Latest

function New-LocalUser
{
	[CmdletBinding()]
	param(
		[ValidateNotNullOrEmpty()]
		[String[]]$ComputerName = $env:ComputerName,

		[Parameter(Mandatory)]
		[ValidateNotNullOrEmpty()]
		[String]$UserName,

		[Parameter(Mandatory)]
		[ValidateNotNullOrEmpty()]
		[String]$Password
	)
		
	[ScriptBlock]$sb = {
		try
		{
			$status = [PSCustomObject]@{Computer = $_; User = $Using:UserName; Success = $true}
			$computer = [ADSI]"WinNT://$_, Computer"
			
			#will throw error if can't connect to the specified computer and return PSCustomObject in the finally block (expected behaviour)
			$user = $computer.Create('User', $Using:UserName)
			
			#will throw error if uncommented and return PSCustomObject in the finally block (expected behaviour)
			#throw
			
			#will NOT return PSCustomObject or execute finally block however user account is created successfully! (unexpected behaviour)
			$user.SetPassword($Using:Password)
			$user.SetInfo()
		}

		catch
		{
			$status.Success = $false
		}

		finally
		{
			Write-Output $status
		}
	}

	$ComputerName | Start-RSJob -ScriptBlock $sb -Debug -Verbose | Wait-RSJob | Receive-RSJob
	#Get-RSJob | Remove-RSJob
}
```

**Comment by proxb** [comment]
Interesting. Can you provide the OS and PowerShell version that you have experienced this on?

**Comment by kborowinski** [comment]
I've tested it with Powershell 5 on Windows 7 SP1 Enterprise x64 and Windows 10.0.10586.420 x64.

**Comment by proxb** [comment]
Thanks! I'll start looking at this sometime soon and see what might be going on.

**Comment by kborowinski** [comment]
Quick update, the script works as expected with regular job cmdlets (Start-Job, Receive-Job).  I just  had to replace $Using with argument list for the script block to make it work of course.

**Comment by proxb** [comment]
I was able to reproduce so I'll dig a little deeper to see what might be going on.

**Comment by proxb** [comment]
I was able to get this working by adding a [void] on the line where you are setting the password.

```PowerShell
[void]$user.SetPassword($Using:Password)
```

It appears that calling this method creates a null return that ends up returning 2 items instead of just one object. Unfortunately, when the module performs a check to verify that the data from a RSJob is good, it looks for Null object and if one is found, it assumes that it is nothing and doesn't actually save the results. I'll need to go back and look for a better way of handling this issue.

**Comment by proxb** [comment]
I think that I have this fixed now and did some testing with your code as well as some other code. I'll get this updated in the next couple of days.

**Comment by proxb** [comment]
Let me know if the latest version fixes your issue.

**Comment by kborowinski** [comment]
Works like a charm. Thank you!
