### ISSUE TITLE
Unable to install - "Install-Module -Name PoshRSJob"

### ISSUE THREAD

**Issue by davesbrown** [proxb/PoshRSJob#79]
Install-Module : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:16
+ Install-Module -Name PoshRSJob
+                ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

**Comment by proxb** [comment]
It seems like there is an issue with the cmdlet Install-Module, not with the module itself. What version of PowerShell are you running?

**Comment by davesbrown** [comment]
Thanks, I have resolved this by upgrading to PS 5.0.  Apparently, there was a different Install-Module installed through http://psget.net/ that doesn't have the -Name parameter.  More information here:
http://superuser.com/questions/996417/what-is-install-module-command-in-powershell
