### ISSUE TITLE
Start-RSJob in for loop do not get a unquie Id

### ISSUE THREAD

**Issue by bushe** [proxb/PoshRSJob#8]
In a function I am starting a RSJob and calling the function with various data in a for loop. The RSJobs IDs are only varied one or two numbers between 16 RSJobs

[start-rsjob](https://cloud.githubusercontent.com/assets/1182071/6985485/ff97d9e0-da01-11e4-9750-dcb40457fada.PNG)

**Comment by proxb** [comment]
Any chance you could provide some sample code so I can try to duplicate this issue?

**Comment by bushe** [comment]
I have not been able to duplicate since the recent version after the bug was filed
