### ISSUE TITLE
Import-Module PoshRSJob error when Set-StrictMode -Version Latest

### ISSUE THREAD

**Issue by W1M0R** [proxb/PoshRSJob#90]
When using Set-StrictMode -Version Latest, I receive errors when using Import-Module PoshRSJob.

The error occurs in: TabExpansion.ps1 line 20.

I resolved it locally by changing:

If (-not $global:options) { 

to:

If (-not(Test-Path variable:global:options)) {

**Comment by proxb** [comment]
I actually had a PR last night that should have fixed this. Ref: https://github.com/proxb/PoshRSJob/pull/86
It hasn't made it into the actual release yet as I didn't have time to get it done but the TabExpansion.ps1 file does reflect the change.

**Comment by W1M0R** [comment]
Woops, I didn't realize. Thanks!
