### ISSUE TITLE
Error when -FunctionsToLoad parameter is used and the Function does not have an alias

### ISSUE THREAD

**Issue by jaywryan** [proxb/PoshRSJob#96]
When you use -FunctionsToLoad and the Function you are loading does not have an alias associated with it, there is a non-terminating error generated when the following is ran in Start-RSJob
```powershell
$Alias = Get-Alias -Definition $Function
```
We can wrap it in a try catch, or just ignore the error.

```powershell
$Alias = Get-Alias -Definition $Function -ErrorAction SilentlyContinue
```

**Comment by jaywryan** [comment]
I submitted a PR for this issue #97

**Comment by proxb** [comment]
Thanks! I've merged your committ. Appreciate the help!
