### ISSUE TITLE
Add an InputObject property to RSJob class

### ISSUE THREAD

**Issue by oldlost** [proxb/PoshRSJob#99]
**[object]$InputObject** property would be the object which is piped to the job. The purpose is to be able to identify which RSJob is handling which piped object.

**Comment by proxb** [comment]
Sounds like it is pretty doable. I'll rack and stack this with other things and try to get it knocked out...or if you wanted to take a swing at it, feel free to submit a PR and I'll review and get it merged.

**Comment by proxb** [comment]
Should be fixed after https://github.com/proxb/PoshRSJob/pull/100
